const android = "10.0.2.2";
const ios = "localhost";
const realDevice = "192.168.0.195";
const port = ":8888"; //:80
const platform = ios;
const readUrl = "http://$platform$port/cadt7/read.php";
const deleteUrl = "http://$platform$port/cadt7/delete.php";
const insertUrl = "http://$platform$port/cadt7/insert.php";
const updateUrl = "http://$platform$port/cadt7/update.php";
